### ISSUE TITLE
Dashboard - MQTT 第一次連線的時候，增加 message queue

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#1009]
# Why
- MQTT 在切換開關的時候會是斷線的，所以連線成功後，要 push message switch state

# Task

- [ ] MQTT 成功連線後， push message switch state

# Check List

- [ ] 確認 task 都有執行

**Comment by miterfrants** [comment]
這個 #1010  測試如果沒問題就不用這個 issue
