### ISSUE TITLE
Testing - MQTT 連線

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#1010]
# Why
- 確認 MQTT 連線之後，會不會接收連線之前 server 傳的 message queue

# Task

- [x] 測試確認 MQTT 連線後，會不會接收連線之前 server 傳的 message queue

# Check List

- [ ] 提出測試結果

**Comment by miterfrants** [comment]
切換switch 再連線不會收到 publisher 的message

所以需要再裝置連到 mqtt 時 server 主動 push 當前裝置狀態給 device
