### ISSUE TITLE
Marketing - 打 Google 廣告 - for 農用 iot

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#1064]
# Why

為未來 3 ~ 5 年後我們自己建立公司自己的溫網室的時候累積經驗，和搭設溫網室的廠商建立關係。

# Goal
- 確認農用 IoT 是有市場 (需要有一個數字來確認)
- 確認市場能接受的商品性質 e.g PaaS, 一條龍的服務 or 某種特質的商品
- 取得 5 間廠商與我們聯繫
- 至少一間廠商使用我們的服務

# Budget

40,000

# TA
- 農民
- 想要從事農業智慧化的廠商

# Task
- 實作農用 IOT 服務的介紹頁且可以留下電話或 EMAIL 給我們
- 產出一份計畫
- 執行成效
- 執行完的檢討
- 新增客戶聯繫名單
- 標準化報價單
- 標準化報價流程

**Comment by miterfrants** [comment]
# Why
為未來 3 ~ 5 年後我們自己建立公司自己的溫網室的時候累積經驗，和搭設溫網室的廠商建立關係。

# Budget
40,000

# Goal
- 取得 5 間廠商與我們聯繫
- 至少一間廠商使用我們的服務

# Report
- 新增客戶聯繫名單
- 標準化報價單
- 標準化報價流程

**Comment by vickychou99** [comment]
農用 IOT 服務的介紹頁: https://itemhub.io/smart-agriculture/
成效報告: https://paper.dropbox.com/doc/--B6qO0ERec5uQ2vFXHFmci0ZcAg-CS3ccUMRdHs2HdNh2g6Lx
客戶名單: https://docs.google.com/spreadsheets/d/1Vd9xZCU5tD0tmNGdrEUKjcgCZ4boyzkqSlwybazjVO4/edit#gid=0
提案 SOP: https://paper.dropbox.com/doc/SOP--B6qCTHFHhCcQsNXi6MaV~EPVAg-B8W1cKB56iuI15KE0a3x3

**Comment by miterfrants** [comment]
`至少一間廠商使用我們的服務` , `取得 5 間廠商與我們聯繫 ` 
這些都沒有喔
