### ISSUE TITLE
Bug - 修正 MCU ID

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#1069]
# 網址
https://itemhub.homo.tw/dashboard/devices/create

# 重現方式
table: `Microcontroller` 內, 可看見人工調整的ID, 要改回原流水號

# 附件圖片
<img width="278" alt="截圖 2023-02-03 上午2 46 52" src="https://user-images.githubusercontent.com/9404692/216420962-9b292593-d9c4-4bfc-bc0d-e65a7802eb9b.png">

<img width="769" alt="截圖 2023-02-03 上午2 48 43" src="https://user-images.githubusercontent.com/9404692/216421322-0d68e621-0466-4cfd-9e93-4268f06edc9e.png">

**Comment by miterfrants** [comment]
這個不是裝置 ID
