### ISSUE TITLE
修改網頁文案

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#11]
# Why 
 - 依照已確認的網頁文案來更新網頁內容
 - https://docs.google.com/presentation/d/1UP6tSVh3SAGa9XQKU6QrVJdmwphUMuTj/edit#slide=id.p1

# Task
- [x] 更新網頁文案

# Check List
- [ ] 確認網頁文案已更新

**Comment by miterfrants** [comment]
這個是好了嗎？
我不知道怎麼驗證

**Comment by vickychou99** [comment]
好了，確認有把 PPT 文案弄上去
