### ISSUE TITLE
Website - 撰寫 Pipeline 教學文

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#1109]
# Why

- Pipeline 功能教學

# Task

- [x] 撰寫一個 Pipeline 教學文章
- [x] 把它變成 html 

# Check List

- [x] 完成以上 Task

**Comment by vickychou99** [comment]
https://paper.dropbox.com/doc/--B12F1yRQk8tyjJs~92Ashjg3Ag-w2wUTkPZ424UKC1DcUEgG
