### ISSUE TITLE
Dashboard - 撰寫 Spec

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#114]
# Why
讓之後工作比較容易分工

# Task

- [x] Routes
- [x] Shared Component
- [x] Routing Component
- [x] Dataservice
- [x] Redux Reducer

# Check List

- [x] 產出一份包含以上 Spec 的 Paper

**Comment by LiangYingC** [comment]
想問 paper 連結在哪裡？準備明天來驗收

**Comment by miterfrants** [comment]
https://paper.dropbox.com/doc/Itemhub-Dashboard-Spec--BZWls_w_4d_VM8rTihP711XQAg-r8Ir0nYz7osOzWLI8h8OK

**Comment by LiangYingC** [comment]
有留一些言，算是細部討論，大方向 spec 已定義，issue close，talk on paper
