### ISSUE TITLE
Bug - Dashboard Pagination 沒有正常運作

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#1228]
# 網址

https://itemhub.io/dashboard/devices

看起來應該是所有 pagination 都有類似的問題

# 重現方式

- 把 devices 新增超過到有分頁
- 來回切換頁碼多次

# 附件圖片

<img width="959" alt="截圖 2023-05-09 下午1 35 02" src="https://user-images.githubusercontent.com/2028693/237004770-2d9595a4-cb34-4677-8137-88677d0ee469.png">

**Comment by vickychou99** [comment]
https://github.com/miterfrants/itemhub/assets/9404692/b19571d5-28fc-41ea-89f7-9318d1aad15a
