### ISSUE TITLE
Research - 擴香觸控小夜燈可行性分析

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#1267]
# Why

- [ ] 希望能將擴香觸控小夜燈產品化並成為物聯網應用的產品

# Task

- [ ] 研究類似的競品

# Check List

- [ ] 產出與競品的比較及可行性評估

**Comment by miterfrants** [comment]
這個不是說一開始沒有物聯網的功能？

**Comment by vickychou99** [comment]
https://paper.dropbox.com/doc/--B6~F7HPW3dGKuKM~0v5atiiRAg-alhT28tzx969JAj831zV4
