### ISSUE TITLE
Bug - 頁面改不要 cache

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#1329]
# 網址

https://itemhub.io/dashboard/

# 重現方式

- deploy 後，頁面需要清 cache 才會正常顯示

**Comment by miterfrants** [comment]
<img width="831" alt="截圖 2023-07-22 下午1 02 37" src="https://github.com/miterfrants/itemhub/assets/2028693/b4c017fa-ed4f-498d-824a-9f0c4e0f2310">
已經加上去了等下次 deploy 的時候檢查看一下 Http Status 會不會一直出現 200 不會出現 304 Not Modify
