### ISSUE TITLE
Bug - Pipeline ExecuteLog 會出現一下有記錄一下沒有

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#1382]
# 網址

https://itemhub.io/dashboard/pipelines?&page=2

# 重現方式

只要有紀錄就會發生

# 附件圖片

<img width="1179" alt="截圖 2023-09-21 下午11 53 22" src="https://github.com/miterfrants/itemhub/assets/2028693/9b355e61-8b69-42b9-8366-8cd6d08216a1">

**Comment by vickychou99** [comment]
https://github.com/miterfrants/itemhub/assets/9404692/28ced0b3-cfac-48ac-bdf5-2f18c33cd04a

pipeline 列表頁的執行紀錄不會自動更新到最新的執行時間
重現方式:
1. 設定每分鐘執行的 pipeline
