### ISSUE TITLE
Research - 組織培養降低發霉率

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#1415]
# Why

- 目前實驗大概都維持在 50% 的發霉率，換言之就是只有一半的瓶苗不會發霉，做實驗的話會造成很大的實驗誤差，所以應該先提高生存率再來繼續下面的實驗，以目前的實驗狀況大概在前三天 72 小時內如果會發霉大致上都已經發霉了。看了幾篇文章大概普遍的微生物污染的比例大致在 10% Referrence: 
  -  https://www.researchgate.net/publication/315135676_Common_Fungi_Contamination_Affecting_Tissue-cultured_Abaca_Musa_textiles_Nee_during_Initial_Stage_of_Micropropagation
  - https://www.researchgate.net/publication/228338582_Sources_of_microbial_contamination_in_tissue_culture_laboratories_in_southwestern_Nigeria#pf4
# Task

- [x] 提出發霉可能的問題
- [x] 為提出的發霉問題提出可以的解決方案
- [x] 設計實驗
- [x] 執行實驗

# Goal

- [x] 產出一個可重複的生產步驟，並可以提高培養體的生存率

# Report

- 植體前兩天先備製培養基 培養基配方請參考 https://github.com/miterfrants/itemhub/issues/1406
- 前一天做無菌水 (無菌水分多瓶，降低污染影響範圍 e.g: 如果有單一樣本消毒不夠完全只會污染到同一瓶的浸泡樣本) 和器皿消毒
- 植體當天前半個小時先用酒精擦拭，開啟送風設備後把消毒好的器皿和消毒水放入操作台，並把超音波洗滌機消毒後置入
- 植體前 15 分鐘開啟紫外燈消毒
- 植體取樣時先用中性洗碗精刷洗，並用過濾後的水做洗滌，洗滌完後浸泡在無菌水中
- 依照樣本的種類決定消毒時間和濃度，把樣本丟到無菌操作台中的超音波洗滌機
  - 樣本厚度超過 1mm 可以用 2% 次氯酸鈉水溶液清洗 15 mins
  - 樣本小於 1mm 用 6% 次氯酸鈉水溶液清洗 2 mins (這個有待實驗)
- 清洗完的樣本浸泡於無菌水 10 mins 
- 植入培養基時每一瓶樣本後都要對鑷子和刀具做過火消毒的動作，並使用酒精消毒培養皿(切除果凍化的組織)

**Comment by miterfrants** [comment]
# 可能發霉原因
目前觀察下來發霉的狀況都由樣本開始長菌絲所以基本上可以排除滅菌設備、無菌操作台的硬體問題，可能有以下幾個可能原因
- 器皿沒有消毒完全
- 樣本表面帶真菌孢子
- 樣本內部帶真菌孢子

# 提出解決方案

## 器皿沒有消毒完全
現在是在使用前先用酒精消毒接觸樣本的地方，可以改用先泡在酒精池裡頭在用噴燈燒過一遍或是整個實驗切割和夾取的器具都先放到器皿中進到滅菌鍋滅菌，從滅菌釜拿出來時整個過程再進到無菌操作台前不會開蓋。

## 樣本表面帶真菌孢子
先用清水清洗過表面，在用牙刷界面活性劑清洗過一次，在用很稀的漂白水刷過一次無菌水泡過，再進到本來的實驗

## 樣本內部帶真菌孢子
這個應該是不太常發生，而且如果會發生，真菌的表徵會呈現特定的樣態，像是炭疽、白娟，這個應該查一下相關的文獻就可以得到結論

**Comment by miterfrants** [comment]
#器皿沒有消毒完全實驗

## 對照組
之前的瓶苗應該可以當作對照組，發霉率為 50% 

## 實驗組
實驗器具在操作前進到滅菌鍋進行高溫高壓滅菌， 121 度 30 mins, 進行 20 瓶苗測試，培養基配方如 https://github.com/miterfrants/itemhub/issues/1406

- 酸鹼: 鹽酸、氫氧化鉀
- 培體: 姬秋麗葉片
- pH: 5.3 ~ 5.7
- 激素: NAA 0.1mg/L BA 10mg/L
- 植入培養基時間: 2023-12-17 02:30


時間(Hr) | 發霉 | 所有樣本 | 存活率
-- | -- | -- | -- | -- | -- | --
0 | 0 | 0 | 0 | 20 | 0 | 100%
66 | 0 | 0 | 0 | 20 | 0 | 100%
93 | 0 | 0 | 0 | 20 | 0 | 100%

**Comment by vickychou99** [comment]
所以是指實驗器具滅菌後就不會發霉了嗎?

**Comment by miterfrants** [comment]
結論是器具滅菌是一個重要的步驟
