### ISSUE TITLE
Website - 規劃 checkout page 並與設計溝通產出設計稿

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#157]
# Why
規劃 checkout page 並跟設計師溝通並確認設計稿

# Task

- [x] 規劃 checkout page 
- [x] 跟設計溝通頁面
- [x] 確認設計稿
- [x] 確認設計頁面

# Check List

- [x] 確認 checkout page  流程&設計稿
- [x] 新增實作的 issue

**Comment by vickychou99** [comment]
NEW ISSUE
- #257

**Comment by vickychou99** [comment]
設計稿連結:
https://www.figma.com/file/eqxlwbzWPRrdMDCede74yX/itemhub?node-id=475%3A10236

**Comment by miterfrants** [comment]
實作的 Issue 是不是把 Checkout 分成 3 個 check point 
- 付款頁面
- 確認頁面
- 完成頁面

**Comment by vickychou99** [comment]
> * 付款頁面

加一個 pricing 頁選擇訂閱方案

**Comment by vickychou99** [comment]
#257 
#272

**Comment by miterfrants** [comment]
要補上未登入選擇訂閱方案, 再登入以後要 redirect 到選擇方案頁面, 目前是登入就會回首頁

**Comment by vickychou99** [comment]
> redirect

DONE
