### ISSUE TITLE
Website - 規劃 兩步驟驗證頁面 並與設計溝通產出設計稿

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#161]
# Why

讓 USER 可以兩步驟頁面登入

# Task

- [x] 產出兩步驟頁面登入的流程頁面
- [x] 與設計溝通頁面
- [x] 確認設計稿

# Check List

- [x] 確認產出設計稿
- [x] 新增頁面實作的 ISSUE

# Dependency
- #135

**Comment by vickychou99** [comment]
https://docs.google.com/presentation/d/1UP6tSVh3SAGa9XQKU6QrVJdmwphUMuTj/edit#slide=id.g10cbd228d71_0_0

PPT page 14、15

**Comment by miterfrants** [comment]
check list 不用把實作的 issue 列上去嗎？

**Comment by vickychou99** [comment]
已加

**Comment by vickychou99** [comment]
等待設計稿產出

**Comment by vickychou99** [comment]
new issue 
- #258

**Comment by vickychou99** [comment]
設計稿連結:
https://www.figma.com/file/eqxlwbzWPRrdMDCede74yX/itemhub?node-id=475%3A10236
