### ISSUE TITLE
在 IOT 社群中推廣服務

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#17]
# Why 
 - 在 IOT 社群中推廣我們的服務，測試大家的反應及吸引使用者來註冊

# Task
- [x] 找三個較有互動性的 IOT 社群， 並 PO 文介紹我們的服務

# Check List
- [x] 確認有 PO 文
- [x] 整理成效數據

**Comment by miterfrants** [comment]
補一下 report 好了
https://docs.google.com/spreadsheets/d/1khk1v8yb2tY4LPHTaRTGh3nul-uT_QDmCy3uwNE4_8w/edit#gid=0
