### ISSUE TITLE
Website - 規劃 Detail of How to use 並產出設計稿

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#174]
# Why

讓 USER 可以更了解如何使用我們的服務，可能需搭配 dashboard 或是 sample code 的說明

# Task

- [x] 產出Detail of How to use的頁面內容
- [ ] 與設計溝通頁面
- [ ] 確認設計稿
- [ ] 新增實作的 issue

# Check List

- [ ] 確認產出設計稿
- [ ] 確認有新增實作的 issue

# Dependency
- #135

**Comment by miterfrants** [comment]
check list 不用把實作的 issue 列上去嗎？

**Comment by vickychou99** [comment]
已加

**Comment by vickychou99** [comment]
HOW TO USE
step1 註冊登入後至裝置中心新增你的裝置
註冊並登入後，至裝置中心內新增裝置，填寫裝置資訊送出即可完成新增裝置

step2 打包並下載系統自動產生的程式碼
完成新增裝置後，可打包並下載程式碼，將下載後的程式碼燒錄至裝置內，即可直接調整裝置開關或查看感應器的資料狀態。

step3 設定裝置的屬性或使用邏輯後，即可直接操控裝置或收集裝置資訊
至裝置中內設定裝置的觸發條件，如濕度大於等於 65 即開啟除濕機，或是濕度小於 65 則關閉除濕機

**Comment by vickychou99** [comment]
HOW TO USE
step1 註冊登入後至裝置中心新增你的裝置
註冊並登入後，至裝置中心內新增裝置，填寫裝置資訊送出即可完成新增裝置

step2 下載程式碼並燒錄至裝置內
完成新增裝置後，可下載系統自動產生的程式碼，下載後燒錄至裝置內，即可直接調整裝置開關或查看感應器的資料。

step3 設定裝置的屬性或使用邏輯後，即可直接操控裝置或收集裝置資訊
設定裝置的觸發條件，如濕度大於等於 65 執行開啟除濕機，或是濕度小於 65 執行關閉除濕機。


Dashboard how to use 

step 1 新增裝置
至「裝置」頁新增裝置，輸入裝置名稱，選擇裝置類型後選擇要使用的 PIN 及 PIN 對應的功能，如: D3 為開關 D7 為感應器 
PS:目前僅提供3種類型裝置，後續會在新增其他裝置類型

step 2 下載程式碼
至裝置列表頁或明細頁可下載程式碼，系統會自動產生裝置對應的程式碼
PS:若重新執行打包程式碼，因對應的 Client ID 會被重新建立，舊有程式碼將無法使用

step 3 將程式碼燒錄至裝置
完成下載程式碼後，開啟 xxx 檔案，其中 xxx 請改成你所使用的 wifi 帳號，xxx 請改成 wifi 密碼，完成後存檔並將所有檔案燒錄至裝置內

step 4 確認裝置的連線狀態
完成程式碼的燒錄後，在裝置列表/明細頁即可看到裝置的狀態會切換成上線，即代表成功連線

step 5 切換開關 / 查看感應器資料
裝置成功連線後，可於裝置列表頁或明細頁切換裝置開關或查看感應器回傳的資料，即時的操控裝置與查看裝置資料

step 6 設定自動化觸發條件
於觸發頁填入觸發的名稱、觸發的事件條件與操作目標設定
範例為:
1. 濕度大於等於 65 執行開啟除濕機
2. 濕度小於 65 執行關閉除濕機

**Comment by miterfrants** [comment]
然後上面的步驟數量 和 下面步驟數量為什麼不一樣
