### ISSUE TITLE
Website - 規劃 Detail of Pricing 並產出設計稿

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#176]
# Why

讓 USER 可以訂閱我們的服務

# Task

- [x] 產出 Detail of Pricing 的頁面內容
- [x] 與設計溝通頁面
- [x] 確認設計稿
- [x] 新增實作的 issue

# Check List

- [x] 確認產出設計稿
- [x] 確認有新增實作的 issue

# dependency
- #147 
- #135

**Comment by miterfrants** [comment]
這個 check list 不用生出 實作的 issue 嗎？

**Comment by vickychou99** [comment]
已加
