### ISSUE TITLE
Website - 規劃 聯絡我們 並產出設計稿

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#179]
# Why

讓 USER 可以在網站上留言與我們聯絡

# Task

- [x] 產出聯絡我們的頁面內容
- [x] 與設計溝通頁面
- [ ] 確認設計稿
- [ ] 新增實作的 issue

# Check List

- [ ] 確認產出設計稿
- [ ] 確認有新增實作的 issue

# Dependency
- #135

**Comment by miterfrants** [comment]
check list 不用把實作的 issue 列上去嗎？

**Comment by vickychou99** [comment]
列了

**Comment by vickychou99** [comment]
先不做
