### ISSUE TITLE
Website - 規劃 首波早鳥方案的用戶綁定帳號流程 並產出設計稿

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#180]
# Why

讓 首波早鳥方案的用戶可以進行帳號綁定

# Task

- [x] 產出首波早鳥方案的用戶的帳號綁定流程的頁面內容
- [x] 與設計溝通頁面
- [x] 確認設計稿
- [x] 新增實作的 issue

# Check List

- [ ] 確認產出設計稿
- [ ] 確認有新增實作的 issue

# Dependency
- #135

**Comment by miterfrants** [comment]
check list 不用把實作的 issue 列上去嗎？

**Comment by vickychou99** [comment]
已加

**Comment by vickychou99** [comment]
https://docs.google.com/presentation/d/1Jlee6B3xulzYWttIfGK7u4Az4u1tOupo/edit#slide=id.g108ffd116a8_0_6

PPT page 4,6,7

**Comment by vickychou99** [comment]
設計稿連結:
https://www.figma.com/file/eqxlwbzWPRrdMDCede74yX/itemhub?node-id=475%3A10236

**Comment by vickychou99** [comment]
new issue 
https://github.com/miterfrants/itemhub/issues/256
