### ISSUE TITLE
Website - 申請 EVERY8D 簡訊服務

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#186]
# Why
註冊需發送簡訊驗證碼

# Task

- [x] 申請 EVERY8D https://www.teamplus.tech/product/every8d-value/

# Check List

- [x] 提供 API 文件

**Comment by vickychou99** [comment]
API:
https://www.teamplus.tech/2019/wp-content/uploads/2021/10/EVERY8D-HTTP-API%E6%96%87%E4%BB%B6-v2.1-cht_2021.10.22-E8DV2.pdf

**Comment by vickychou99** [comment]
帳號: itemhubtw
密碼跟我要

**Comment by miterfrants** [comment]
你是不是要開一個實作簡訊 API 的 Issue?

**Comment by vickychou99** [comment]
#68 已加上註冊的 API
