### ISSUE TITLE
Operation - 確保公司報稅都有按時繳納

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#197]
# Why
Peter 忘記繳營業稅, 之前在公司也曾經忘記過. 除了 Peter 本人以外,後來接這個業務的人也忘記過(共 3 人)

# Task

- [x] 設計一個報稅的流程, 避免忘記報稅
- [x] 透過 Google Spreadsheet 設定週期寄信通知要繳納稅金
- [x] 查一下營業稅和營所稅個別在什麼時候繳納

# Check List

- [x] 檢驗流程是否可以正常運作
- [x] 檢驗流程是否可以真的避免漏報稅

**Comment by miterfrants** [comment]
流程為
1. 每 1,3,5,7,9,11 月的十號會寄通知信給 Peter 或未來處理稅務的人
2. 當月的十三號會寄信通只給 Vicky 請他口頭確認 Peter 是否已經報稅

https://docs.google.com/spreadsheets/d/1pFN5DiVewKzexgnoke3HjZuBbdcl73ToJluEH4JAmEw/edit#gid=545608839

可隨時改變提醒人

**Comment by miterfrants** [comment]
這個驗收可以改日期來做驗收

**Comment by vickychou99** [comment]
那改 2月12 發信給處理稅務的人
2月15 寄通知信給我

**Comment by miterfrants** [comment]
![Uploading 888C0816-84A7-4B3E-B06E-9F40CF13633D.png…]()

**Comment by miterfrants** [comment]
<img width="379" alt="截圖 2022-02-15 上午3 20 56" src="https://user-images.githubusercontent.com/2028693/153931608-b6b6635f-d7b6-4b54-8558-736be6328df5.png">

**Comment by vickychou99** [comment]
已將提醒月份改回單月份10號及13號
