### ISSUE TITLE
Operation - 申請電子發票

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#203]
# Why

- 用戶訂閱後要開發票

# Task

- [ ] 申請電子發票

# Check List

- [ ] 確認可正常開立電子發票

**Comment by miterfrants** [comment]
這個 issue 是包含, 電子發票串接嗎？
如果是你的 Task 是不是寫得太不清不楚
然後 Assignees 請標為你

**Comment by miterfrants** [comment]
@vickychou99

**Comment by vickychou99** [comment]
已申請電子發票帳戶，待申請 turnkey 帳號

**Comment by vickychou99** [comment]
已申請軟體憑證，待核可

**Comment by vickychou99** [comment]
已申請  turnkey 帳號，待核可

**Comment by vickychou99** [comment]
電子發票相關的帳號都開好了，字軌尚未申請
後來發現月營收沒超過20W，不用開發票。先 pending，等之後超過 20W 再來啟用電子發票。

**Comment by miterfrants** [comment]
目前沒有要，等到要做再開起來
