### ISSUE TITLE
Title And Description Of Page

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#24]
# Why
搜尋時至少在 Google 上可以看到東西

# Task
- [x] 整理每一頁需要的描述和標題
- [x] 實作 Swim Router meta render

# Check List
- [x] 檢查每一頁是否有塞入對應的標題和描述

**Comment by vickychou99** [comment]
Title: Item Hub
Description: 串聯你的裝置或感應器就是這麼輕鬆簡單，ItemHub 讓你專注在智慧裝置的運用，從今天開始你的智慧生活
