### ISSUE TITLE
Discussion - Rate Limit 機制

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#240]
# Why

- 訂定超過 Rate Limit 的使用者應該怎麼處理, 讓他更有動機升到下一個訂閱方案
- 避免使用者直接因超用被完全禁用

# Task

- [x] 制定超過 Rate Limit 限制方式

# Check List

- [x] 產出一份 Rate Limit 方案 (所有參與者應該都要知道)

**Comment by LiangYingC** [comment]
剛好想到就先丟上來：

當 Rate Limit 到達後，跳出彈窗（或某種顯示方式），其內容資訊包含：

- 升級方案
- 單次購買方案（例如：可以加購多少的 Limit）

然後升級方案的價格，會明顯低於單次購買的方案，舉例而言：

- 升級方案：每月多 1,000，次數多增加 100
- 單次購買方案：需要 500，次數多增加 30

當然畫面的呈現上就蠻重要的，讓使用者覺得買到賺到。

**Comment by miterfrants** [comment]
現在有三個變數

- 裝置數量
- Request 頻率
- 資料儲存時間

### 不直接影響當前使用
- 資料儲存時間, 因為這個是我們在後面跑一個 cron job 固定時間刪除資料

### 事前會知道
- 裝置數量, 使用者在 Dashboard 新增的時候就會知道他是否超過他訂閱的方案, 如果超過就是在頁面跳出新的方案告訴他已經超過方案裝置數量

### 事後才能知道
- Request 頻率, Request 頻率太高, 這個有可能自己寫 code 的時候把打 API 的時間設定成太短, 就會造成頻率太高超過訂閱方案

我的想法: 幫他加一個 flag 標記他已經超過訂閱方案的頻率, 以下會有幾個提醒他應該要升級的方式
- 他只要進到網站就會在最上方或是最下方一直顯示升級的 bar, 如果他標為已讀 bar 會消失, 記在 client 端, 如果它清掉會再一次顯示
- Email 通知: 通知的頻率為費氏數列 ex: 1個月, 1個月, 2個月, 3個月 以此類推
- 技術層面: 擋掉他過高頻率 Request, Server 會紀錄這個 Device 上一次送 Request 的時間, 每一次都檢查這個 Device 的 Owner 鎖定月的方案頻率是否超過, 超過就擋掉

**Comment by vickychou99** [comment]
為了避免價格競爭，或是設計出太多不同的方案，想要遊戲規則單純一點
付費方案的部份，想說都可以免費試用 x 天 (可在討論要幾天)

例如說我用 $49/月 的方案，當今天超過 Rate Limit 時
可以跟用戶說: 
立即升級成 $199/月 的方案，不影響使用還可以免費試用 x 天，立即升級>

**Comment by LiangYingC** [comment]
哦哦我覺得遊戲單純點不錯，而且還可以免費試用，同時也是誘因，而且通常使用者升級後就不會改回去（有時候是忘記ＸＤ）

使用者感覺比較容易理解，開發端也方便開發。

**Comment by miterfrants** [comment]
> 立即升級成 $199/月 的方案，免費試用 x 天，立即升級>

這個有需要讓他免費試用嗎？因為他免費試用了, 也只是 Device 可以新增比較多個, 但如果他沒有付錢未來要處理免費試用期間的 Device 更麻煩

**Comment by vickychou99** [comment]
> > 立即升級成 $199/月 的方案，免費試用 x 天，立即升級>
> 
> 這個有需要讓他免費試用嗎？因為他免費試用了, 也只是 Device 可以新增比較多個, 但如果他沒有付錢未來要處理免費試用期間的
> 
> * Device 是要刪除還是保留
> * 他的 PIN 送過來的資料是要刪除還是保留,

我是覺得當下會有讓人感覺很划算好入手的感覺，希望大部份的人升級了就回不去了XDD
覺得免費試用期間的
* Device 刪除
* PIN 送來的資料刪除
* 或是可以先暫停，若 1個月後沒升級在刪，怕太複雜，一開始簡單做的話可以就先刪

**Comment by miterfrants** [comment]
我是覺得不要做免費試用因為資料被刪除這件事情會很複雜, 使用者自己也搞不清楚他哪些資料是在他免費試用期間新增的, 所以一開始我是想要直接在他送過來的資料做 filter

**Comment by miterfrants** [comment]
那我們分成兩個階段做好不好

第一階段:
先把超過方案的 request 過濾掉, 然後目前只能手動降級訂閱, 短時間我想我們遇不到這樣的狀況

第二階段:
再來做你說的降級訂閱, 把他在升級訂閱的資料隱藏起來, 並不在接收這個 Device 送過來的資料.

**Comment by vickychou99** [comment]
> 那我們分成兩個階段做好不好
> 
> 第一階段: 先把超過方案的 request 過濾掉, 然後目前只能手動降級訂閱, 短時間我想我們遇不到這樣的狀況
> 
> 第二階段: 再來做你說的降級訂閱, 把他在升級訂閱的資料隱藏起來, 並不在接收這個 Device 送過來的資料.
> 
> @vickychou99

OK

**Comment by miterfrants** [comment]
分成兩個階段來執行

# Milestone 2 應該要完成的 Rate Limit 功能

- 實作 API Filter Request 的功能, 每一次送 Request 過來的時候會檢查上一次, 相同 Device 送 Request 的時間如果超過時間會直接回應錯誤訊 Too Many Request 訊息回 Device 
- 實作 API User 超過目前訂閱方案的 Flag 

# Milestone 3 應該要完成的 Rate Limit 功能

- 實作降級訂閱 Archive Device, Trigger, Device Sensor Data
