### ISSUE TITLE
API - 輸出 Trigger Operator Constant 

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#249]
# Why
https://github.com/miterfrants/itemhub/milestone/2

# Task

- [x] 把 Trigger Operator Enums 輸出給前端使用

# Check List

- [x] 檢查 `/api/v1/universal/trigger-operators` 是否有類似以下的資料型態
```json
[
    {
        "key": "B",
        "value": 0,
        "label": "大於"
    },
    {
        "key": "BE",
        "value": 1,
        "label": "大於等於"
    }
]
```

**Comment by LiangYingC** [comment]
驗證成功打 API 拿到資料
