### ISSUE TITLE
Website - 優化 email template

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#302]
# Why
將目前的 email 內容套上 style 樣式

# Task

- [x] [設計稿](https://www.figma.com/file/eqxlwbzWPRrdMDCede74yX/itemhub?node-id=481%3A7762)
- [x] 註冊驗證碼通知信
- [x] 二階段驗證碼通知信
- [x] 註冊成功通知信
- [x] 早鳥用戶綁定通知信
- [x] 成功訂閱方案通知信
- [x] 每月扣款通知信

# Check List

- [x] 確認上述 mail 的 template 都有套上樣式，且顯示正確資訊

**Comment by miterfrants** [comment]
測試機送信圖片沒有出現
