### ISSUE TITLE
Bug - oAuthClient 單頁重新整理會一直重新 render component

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#303]
# 網址

http://localhost:3000/dashboard/oauth-clients/27

# 重現方式

- 切到現在 dev branch
- 啟動 api & dashboard 
- 直接輸入上面的網址開啟 console 會一直看到打 oauth-clients/27 的 api

# 附件圖片
無圖

**Comment by LiangYingC** [comment]
已完成，可驗收
