### ISSUE TITLE
Bug - 已註冊的 email，可以再次點擊發註冊信

### ISSUE THREAD

**Issue by LiangYingC** [miterfrants/itemhub#329]
# 網址

- 目前已經註冊過的 email，還是可以再次發註冊驗證信件

# 重現方式

- run dev 後，在註冊頁面，使用者輸入任何一個已經註冊的 email（可用 `sl20130313@gmail.com` 測試），按下送出驗證信後，不會跳出錯誤訊息

# 附件圖片

- 無

**Comment by vickychou99** [comment]
![截圖 2022-03-19 下午3 56 53](https://user-images.githubusercontent.com/9404692/159112965-c540b977-158a-4570-8295-e8a24a3f97db.png)
