### ISSUE TITLE
Bug - Prod 網站兩階段註冊，第二階段失敗

### ISSUE THREAD

**Issue by LiangYingC** [miterfrants/itemhub#372]
# Why

- 用 sl20130313@gmail.com 註冊 prod 網站
- 第一步驟成功在 email 收到驗證碼
- 第二步驟成功在 手機收到驗證碼
- 但輸入完驗證碼、註冊密碼後，送出 API 會有錯誤發生，截圖如下（密碼僅是因為發現錯誤，所以測試用，不用擔心外流，之後不會用這組註冊）

<img width="1434" alt="截圖 2022-04-03 下午2 11 27" src="https://user-images.githubusercontent.com/56446970/161414361-01b9f43c-7582-410e-947b-8d05d54eee64.png">

```
apiPath : https://itemhub.io/api/v1/auth/sign-up
```

```
payLoad :{ password: "@Testing0403" }
``` 

```
error : {
  errorKey: ""
   message: "Could not find a part of the path \\u0027/app/secrets/key.pub.der\\u0027."
   payload: null
   stackTrace: "   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)\n   at Syst..."
}
```

# Task

- [x]  一般使用者可以正常在 Prod 帳號註冊

# Check List

- [x]  一般使用者可以正常在 Prod 帳號註冊

**Comment by miterfrants** [comment]
看起來是少了 RSA private  key

**Comment by LiangYingC** [comment]
驗證成功，在 prod 成功註冊並進入 dashboard

![截圖 2022-04-06 上午12 07 27](https://user-images.githubusercontent.com/56446970/161797748-cf1f90c2-3ee8-4d1a-8e1b-a669718b7680.png)
