### ISSUE TITLE
Bug - 早鳥註冊使用者需要有特定機制自動訂閱進階方案

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#385]
# 網址

None

# 重現方式

- 早鳥使用者註冊完以後
- 把自動訂閱的 cronjob 時間調整成每分鐘執行
- 看一下是否產生新的 subscription

# 附件圖片

None

**Comment by vickychou99** [comment]
早鳥用戶註冊完後要新增一筆訂閱資料

**Comment by miterfrants** [comment]
這個是不是列到 第二階段要上線的時候跑 migration early adaptor first subscription
