### ISSUE TITLE
Bug - RWD Content 被 Header 蓋住

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#461]
# 網址

http://localhost:3000/dashboard/devices

# 重現方式

用 Chrome RWD 模擬, 寬度 600 就會發現列表上的按鈕沒辦法按到

# 附件圖片
<img width="754" alt="截圖 2022-04-21 下午7 11 09" src="https://user-images.githubusercontent.com/2028693/164446244-47de9658-8762-4a5a-98f4-5d0b3994ef15.png">

**Comment by miterfrants** [comment]
<img width="714" alt="截圖 2022-04-21 下午11 17 10" src="https://user-images.githubusercontent.com/2028693/164490605-dc341c7b-da58-4b3f-8455-a73dab3635bb.png">

上面的 head 被蓋住了

**Comment by LiangYingC** [comment]
驗證完成

![截圖 2022-04-24 下午3 44 15](https://user-images.githubusercontent.com/56446970/164965874-53850d40-8ef4-4df5-8f65-ca111dd14511.png)
