### ISSUE TITLE
Dashboard - 改 SASS 後，重新 render 非常慢

### ISSUE THREAD

**Issue by LiangYingC** [miterfrants/itemhub#480]
# Why

每次改完 SASS 後，重新 compile, render 非常慢 (超過 5s)。

目前推測是因為 Vite 針對存 SASS 的效能較差，可參考這個 issue

https://github.com/vitejs/vite/discussions/6817

# Task

- [x] 研究問題為什麼發生以及解法
- [x] 利用任一解決方案解掉問題

# Check List

- [ ] 目標是至少改完 SASS 在 1s 內可以重新 render

**Comment by miterfrants** [comment]
https://github.com/sass/dart-sass/issues/113
看起來沒救, 就算升級也只快一點, 我先 fork 一個版本然後改用 node-sass
不過我得先看懂
