### ISSUE TITLE
Bug - Website - 首頁「立即登記」收到 400 EMAIL_ALREADY_REGISTERED 不會跳出錯誤提示

### ISSUE THREAD

**Issue by choznerol** [miterfrants/itemhub#483]
# 網址

https://itemhub.io

# 重現方式

用同一個

# 附件圖片

![itemhub-EMAIL_ALREADY_REGISTERED](https://user-images.githubusercontent.com/12410942/164968598-caaec099-540d-4407-859f-5caf099bfb83.gif)

# 其他資訊

從這邊 ... https://github.com/miterfrants/itemhub/blob/1936f5c44f8e40535613c3e0676513c7bbb42fa9/website/src/components/check-in/check-in.component.js#L48-L51 ... 看起來前端有處理非 200 OK 跳錯誤訊息，但實際上似乎不會跳出

**Comment by miterfrants** [comment]
<img width="963" alt="截圖 2022-04-25 下午2 50 39" src="https://user-images.githubusercontent.com/2028693/165035386-d6788841-2597-4d15-a73b-cb82918bc92e.png">

我看會跳出來誒, 會不會是被什麼 chrome extension 擋掉？

**Comment by choznerol** [comment]
我剛試了也可以（無論是否無痕），可能是搞錯了🙇
