### ISSUE TITLE
Website - tappay 自動續訂時，使用不需 3D 驗證的 Merchant ID

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#512]
# Why

- 自動續訂時，使用 `不需 3D 驗證` 的 `Merchant ID` 進行付款

# Task

- [x] CronJob 續訂時，使用 `不需 3D 驗證` 的 `Merchant ID`

# Check List

- [x] 確認 CronJob 可正常續訂

**Comment by miterfrants** [comment]
現在不能續訂嗎？
