### ISSUE TITLE
DevOps - Facebook Review App 

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#540]
# Why

- 提供 Facebook 登入功能, 目前 Facebook 寄了一封信件來, 希望我們提供測試帳號密碼讓 Facebook 人工 review, 目前有兩個解法
  - 寫份完整的說明和測試流程給 Facebook 做人工審核
  - 把 Facebook 登入拿掉 (免得之後一直 GGYY, 政策有變動我們就要跟著做相對應的變動)

# Task

- [x] 撰寫一份文件告訴 Facebook Itemhub 在做些什麼, 並提供測試的帳號密碼

# Check List

- [x] Resolve Facebook Review Alert

**Comment by miterfrants** [comment]
先把它移除

**Comment by LiangYingC** [comment]
目前是以移除方案為主，紀錄一下
