### ISSUE TITLE
Marketing - 規劃接下來的行銷方案

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#634]
# Why

- 獲取更多新用戶

# Task

- [x] 規劃推廣的行銷方案

# Check List

- [x] 確認行銷方案

**Comment by miterfrants** [comment]
我在想要不要來寫一個教學文做長期 SEO 用

**Comment by miterfrants** [comment]
1-1 你要怎麼做? 因為一般的除濕機是沒辦法這樣做

**Comment by vickychou99** [comment]
> 1-1 你要怎麼做? 因為一般的除濕機是沒辦法這樣做

那換另一個情景
新增 trigger 時間超過 6:30，自動開啟電燈，早上 5:30 自動關閉電燈

**Comment by miterfrants** [comment]
> > 1-1 你要怎麼做? 因為一般的除濕機是沒辦法這樣做
> 
> 那換另一個情景 新增 trigger 時間超過 6:30，自動開啟電燈，早上 5:30 自動關閉電燈

現在沒有時間 trigger

**Comment by vickychou99** [comment]
> > > 1-1 你要怎麼做? 因為一般的除濕機是沒辦法這樣做
> > 
> > 
> > 那換另一個情景 新增 trigger 時間超過 6:30，自動開啟電燈，早上 5:30 自動關閉電燈
> 
> 現在沒有時間 trigger

那換成啟動廁所抽風扇
