### ISSUE TITLE
Website - Implement pricing-plan Style

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#66]
# Why
整修頁面讓它看起來比較不像詐騙集團

# Task
- [x] pricing-plan 的 Style

# Check List
- [x] 檢查 pricing-plan 區塊的 Style

**Comment by miterfrants** [comment]
你是不是要附一下 figma 連結

**Comment by miterfrants** [comment]
https://www.figma.com/file/eqxlwbzWPRrdMDCede74yX/itemhub?node-id=46%3A1378
