### ISSUE TITLE
Bug - 新增裝置後，裝置 device id API 回應為 null

### ISSUE THREAD

**Issue by LiangYingC** [miterfrants/itemhub#667]
# 網址

https://itemhub.io/dashboard/devices

# 重現方式

新增裝置，新增後發現 Device Id 欄位是空的，查看 API 資料發現 deviceId 是 null

(更多 detail，我是在 prod 環境下創建的，信箱為 sl20130313@gmail.com)

# 附件圖片

https://itemhub.io/api/v1/my/devices/{id}

![截圖 2022-06-02 上午11 37 31](https://user-images.githubusercontent.com/56446970/171548444-f65e19b0-508c-4efd-8b7b-355a7a0686af.png)

**Comment by miterfrants** [comment]
這個是正常的, 因為 deviceId 會是裝置登入的時候才 assign 給 db 的

**Comment by miterfrants** [comment]
我剛剛看了一下 code 現在這一欄不需要了, 之前是透過 deviceId 來辨識是哪一個 device
但現在就用 oAuthClient Id 來做辨識所以是 server 端給的

**Comment by LiangYingC** [comment]
還是要改成呈現 oAuthClient Id ? 會否未來有問題時問使用者比較好查

應該就是 api 回的那個 id (router 現在帶的那個 id) ?

**Comment by miterfrants** [comment]
oAuthClient Id 應該是沒有要讓使用者知道，只有看 code 看得到這個資料
我現在想像的情境，使用者如果有問題他會透過 freshdesk 的 chat box 跟我們講，然後我會跟他在丟我訊息的時候 freshdesk 就會帶當前的網址，這時候我們就有他的 Id 所以也不用特別跟他說這個是 id

**Comment by LiangYingC** [comment]
ok 我發個 PR 拔掉
