### ISSUE TITLE
Website -  Implement sign up Style

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#68]
# Why
整修頁面讓它看起來比較不像詐騙集團

# Task
- [x] sign up 的 Style

# Check List
- [x] 檢查 sign up 區塊的 Style

**Comment by miterfrants** [comment]
你是不是要附一下 figma 連結

**Comment by vickychou99** [comment]
https://www.figma.com/file/eqxlwbzWPRrdMDCede74yX/itemhub?node-id=46%3A1397

**Comment by miterfrants** [comment]
sign-up 流程不對
點 sign-up 連結 -> 連到填寫 email 表單 -> 發送 email 驗證碼，並填寫在剛剛 email 表單 -> 成功驗證後跳到填寫密碼

**Comment by vickychou99** [comment]
等待設計稿產出

**Comment by vickychou99** [comment]
- 註冊要發送 SMS
- SMS API: https://www.teamplus.tech/2019/wp-content/uploads/2021/10/EVERY8D-HTTP-API%E6%96%87%E4%BB%B6-v2.1-cht_2021.10.22-E8DV2.pdf
- 帳號: itemhubtw
- 密碼: 找我要

**Comment by miterfrants** [comment]
> * 註冊要發送 SMS
> * SMS API: https://www.teamplus.tech/2019/wp-content/uploads/2021/10/EVERY8D-HTTP-API%E6%96%87%E4%BB%B6-v2.1-cht_2021.10.22-E8DV2.pdf
> * 帳號: itemhubtw
> * 密碼: 找我要

這個應該要獨立出來, 要不然你要寫嗎？

**Comment by miterfrants** [comment]
Pending 等 echo

**Comment by vickychou99** [comment]
註冊流程
https://www.figma.com/file/eqxlwbzWPRrdMDCede74yX/itemhub?node-id=233%3A9890

email 版型
https://www.figma.com/file/eqxlwbzWPRrdMDCede74yX/itemhub?node-id=481%3A7776
