### ISSUE TITLE
Website - Implement login Style

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#69]
# Why
整修頁面讓它看起來比較不像詐騙集團

# Task
- [x] login 的 Style

# Check List
- [x] 檢查 login 區塊的 Style

**Comment by vickychou99** [comment]
https://www.figma.com/file/eqxlwbzWPRrdMDCede74yX/itemhub?node-id=46%3A1397

**Comment by miterfrants** [comment]
@vickychou99  please, help me to review this.
https://github.com/miterfrants/itemhub/pull/187
if ok, merge it.

**Comment by vickychou99** [comment]
<img width="1435" alt="截圖 2022-01-12 下午10 13 51" src="https://user-images.githubusercontent.com/9404692/149156544-c769e045-d016-4c06-b5a5-430db64259e1.png">

**Comment by vickychou99** [comment]
<img width="743" alt="截圖 2022-01-12 下午10 38 58" src="https://user-images.githubusercontent.com/9404692/149161143-e08e0058-c708-491b-b37c-199f596a395b.png">

- [ ] 手機版最下面文字要有間距

**Comment by miterfrants** [comment]
> 右邊區塊若高於左邊區塊，會有一塊空白
不懂

**Comment by miterfrants** [comment]
已經修正
