### ISSUE TITLE
Dashboard - 新增 ESP-32C, RTL8720DN Firmware

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#813]
# Why

- 讓使用者更有機會使用我們的平台

# Task

- [x] ESP-32C Firmware
- [x] RTL8720DN Firmware

# Check List

- [ ] 檢查 Dashboard 是否有這兩個 Firmware

**Comment by vickychou99** [comment]
RTL8720DN 的說明應該要一起上，不然 user 可能會無法燒錄

**Comment by vickychou99** [comment]
esp32 c3 的 pin 長度超過 3 碼，新增 trigger 會噴錯

<img width="1005" alt="截圖 2022-07-05 上午12 27 14" src="https://user-images.githubusercontent.com/9404692/177192324-036eb512-3d8c-419a-95d2-8e2deaa355b5.png">

**Comment by vickychou99** [comment]
> RTL8720DN 的說明應該要一起上，不然 user 可能會無法燒錄

這個補完在驗收
