### ISSUE TITLE
Marketing - 撰寫通知的 PO 文

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#856]
# Why

- Ref: #634 
- 增加使用者

# Task

- [ ] 推廣 email 通知

# Check List

- [ ] 確認文案內容
- [ ] 確認已 PO 文

**Comment by vickychou99** [comment]
我又來了(揮手)
只是想跟大家說說~~我們把裝置的觸發通知上線啦 🥳🥳🥳

觸發條件除了控制裝置之外，也可以直接發 EMAIL 通知了! 
 (簡訊通知還在努力開發中💪🏻)

可以跟我一起這樣用

✔️土壤濕度過低，通知你要澆水
✔️魚缸水質檢測，通知你要換水
✔️老婆要到家了，通知你 PS5 趕快收起來~~~🥺

讓你隨時隨地掌握裝置的通知訊息

趁暑假來玩玩 itemhub 的服務 → 註冊 LINK
操作說明 → HOW TO USE LINK

**Comment by miterfrants** [comment]
Go!
