### ISSUE TITLE
Website - chrome extensions - DuckDuckGo 看網站會是空白

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#890]
# Why
- 目前已經有多個人反應使用 chrome extensions 時，看我們網站會是空白
- 有回報的 extensions  是 DuckDuckGo ，裝了之後看 hahow & UNT 都是正常，所以可能要解決為什麼我們的是空白的

# Task

- [ ] 解決使用 DuckDuckGo 無法正常瀏覽網站

# Check List

- [ ] 確認使用 DuckDuckGo 可正常瀏覽網站

**Comment by vickychou99** [comment]
原本想說先不處理，但後來討論說一個一個拔掉看，所以結論要在另外看到底發生什麼事

**Comment by miterfrants** [comment]
https://github.com/etesync/etesync-web/issues/7

**Comment by miterfrants** [comment]
![Uploading 截圖 2022-08-11 下午2.04.25.png…]()
