### ISSUE TITLE
Marketing - 0723 SMS PO 文 

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#907]
# Why

- 吸引更多用戶

# Task

- [ ] 撰寫 PO 文
- [ ] 0723 20:00 至 Arduino.Taiwan、Arduino.Taipei、台灣ESP32愛玩、Ameba IoT  PO文

# Check List

- [ ] 確認有 PO 文

**Comment by vickychou99** [comment]
大家最近有在燒錄裝置或是採購新設備嗎?
我最近又跑去採購了一批很純的......感應器XD
然後想起來好像還沒跟大家說我們的觸發通知新增簡訊了！
讓你想怎麼通知就怎麼通知～～～～

像是 :
- 廚房煙霧偵測 
- 3D 列印溫度偵測
- 私房錢感應偵測  (位置被發現該換地方了 orz

然後想問問大家常用的傳輸協定是什麼?
MQTT or HTTPS or HTTP ....?
PTT(大誤).

不免俗的還是要來說一下
使用 itemhub 服務的好處
👉 隨燒即用，方便好用
👉 資料加密，安全無慮
👉 多元通知，萬無一失

**Comment by miterfrants** [comment]
PTT 和 HTTPS 拿掉 
把不是 protocol 的拿掉

**Comment by vickychou99** [comment]
> PTT 和 HTTPS 拿掉 把不是 protocol 的拿掉

done
