### ISSUE TITLE
Bug - 從 ESP-01S 更換裝置到 Node MCU 不存在的 PIN 不會被刪除

### ISSUE THREAD

**Issue by miterfrants** [miterfrants/itemhub#934]
# 網址

https://itemhub.io/dashboard/devices/edit/{id}

# 重現方式

- 建立一個 ESP-01S 的裝置
- IO01 改為開關
- 儲存後再回到編輯把裝置蓋成 Node MCU IO01 還存在

# 附件圖片

<img width="1205" alt="截圖 2022-08-04 下午7 42 01" src="https://user-images.githubusercontent.com/2028693/182838977-5c532c92-2af8-4704-bdc8-8d65b82df352.png">

**Comment by vickychou99** [comment]
測試後沒問題
