### ISSUE TITLE
Website - 把 yt 影片的連結內崁到 website 內

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#937]
# Why

- 讓更多人了解如何使用 

# Task

- [x] 把 yt 影片的連結內崁到 implement-hygrometer 內

# Check List

- [x] 確認 task 都有執行

**Comment by miterfrants** [comment]
youtube 影片沒有填滿空間
<img width="710" alt="截圖 2022-08-16 下午10 22 47" src="https://user-images.githubusercontent.com/2028693/184903798-a4b454d4-a7b7-42c6-b768-3831ae6a1454.png">

**Comment by vickychou99** [comment]
是說要整個滿版嗎? 
是怕填滿空間會太大 ，目前覺得這尺寸 OK 耶

**Comment by miterfrants** [comment]
圖片是滿版誒
