### ISSUE TITLE
Dashboard - 裝置類型新增其他的選項

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/itemhub#944]
# Why

- 裝置類型新增其他的選項，讓用戶可以自行串接 api 

# Task

- [ ] 裝置類型新增其他的選項

# Check List

- [ ] 確認 task 都有執行
- [ ] 確認可正常新增裝置

**Comment by miterfrants** [comment]
這個不用自己串 API, 可以讓他客制化自己的 PIN

**Comment by miterfrants** [comment]
duplicated #1002
